# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBtvOD-XEgme9obkV0E8iven08GB3FzN
"""

from google.colab import drive
drive.mount('/content/drive')

import gradio as gr
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array

# Load model
model_path = "/content/drive/MyDrive/waste_classifier.keras"
model = load_model(model_path)

# Labels and tips
class_names = ['Biodegradable', 'Non-Biodegradable']
tips = {
    'Biodegradable': "🌿 Compost organic waste like food scraps and leaves. Keep plastics out.",
    'Non-Biodegradable': "🔁 Recycle plastic, glass, and metal. Dispose e-waste at proper centers."
}

# Prediction function
def predict(image):
    image = image.convert("RGB").resize((224, 224))
    img_array = img_to_array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)[0]
    label = class_names[np.argmax(preds)]
    confidence = float(np.max(preds))
    tip = tips[label]
    result_text = f"🧾 **Prediction:** {label} \n📊 **Confidence:** {confidence * 100:.2f}%"
    return result_text, tip

# UI with gr.Blocks
with gr.Blocks(title="♻️ Waste Classifier App") as demo:
    gr.Markdown("## ♻️ Waste Classifier")
    gr.Markdown(
        "Upload an image of waste to classify it as **Biodegradable** or **Non-Biodegradable**.\n\n"
        "Get instant **recycling tips** to help the environment! 🌍"
    )

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(label="📷 Upload Waste Image", type="pil")
            submit_btn = gr.Button("🔍 Classify Waste")

        with gr.Column(scale=1):
            output_label = gr.Markdown(label="Prediction")
            output_tip = gr.Markdown(label="♻️ Recycling Tip")

    submit_btn.click(fn=predict, inputs=image_input, outputs=[output_label, output_tip])

    gr.Examples(
        examples=[
            "/content/drive/MyDrive/examples/banana_peel.jpg",
            "/content/drive/MyDrive/examples/plastic_bottle.jpg"
        ],
        inputs=image_input,
        label="📁 Try Example Images"
    )

demo.launch()