# -*- coding: utf-8 -*-
"""streamlit_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBtvOD-XEgme9obkV0E8iven08GB3FzN
"""

import streamlit as st
from PIL import Image
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array

# Load your trained model (once only)
@st.cache_resource
def load_trained_model():
    return load_model("waste_classifier.h5")

model = load_trained_model()

# Class labels
class_names = ['Biodegradable', 'Non-Biodegradable']

# Recycling tips for each class
recycling_tips = {
    'Biodegradable': "🌱 Tip: Compost kitchen and garden waste. Use biodegradable bags.",
    'Non-Biodegradable': "♻️ Tip: Recycle plastic, metal, and electronic waste responsibly."
}

# Image preprocessing
def preprocess_image(image):
    image = image.resize((224, 224))  # Resize to match model input
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)
    image = image / 255.0
    return image

# Streamlit UI
st.title("♻️ Waste Classifier")
st.write("Upload an image to detect whether it's **biodegradable** or **non-biodegradable**.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)

    if st.button("Classify"):
        processed = preprocess_image(image)
        prediction = model.predict(processed)[0]
        class_idx = np.argmax(prediction)
        label = class_names[class_idx]
        confidence = prediction[class_idx] * 100

        st.success(f"Prediction: **{label}** ({confidence:.2f}%)")
        st.info(recycling_tips[label])