# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBtvOD-XEgme9obkV0E8iven08GB3FzN
"""

import streamlit as st
from PIL import Image
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array

# Load model saved in .keras format
@st.cache_resource
def load_trained_model():
    return load_model("waste_classifier.keras")

model = load_trained_model()

# Class labels
class_names = ['Biodegradable', 'Non-Biodegradable']

# Recycling tips
recycling_tips = {
    'Biodegradable': "🌱 Tip: Compost food scraps and garden waste. Avoid contaminating with plastics.",
    'Non-Biodegradable': "♻️ Tip: Recycle plastics, metals, and e-waste at certified centers."
}

# Preprocess uploaded image
def preprocess_image(image):
    image = image.resize((224, 224))  # Match model input size
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)
    image = image / 255.0
    return image

# Streamlit UI
st.title("♻️ Waste Classifier")
st.markdown("Upload an image to classify it as **Biodegradable** or **Non-Biodegradable**.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    if st.button("Classify"):
        processed = preprocess_image(image)
        prediction = model.predict(processed)[0]
        class_idx = np.argmax(prediction)
        label = class_names[class_idx]
        confidence = prediction[class_idx] * 100

        st.success(f"Prediction: **{label}** ({confidence:.2f}%)")
        st.info(recycling_tips[label])
import gdown
import os
from tensorflow.keras.models import load_model

MODEL_PATH = "waste_classifier.keras"
if not os.path.exists(MODEL_PATH):
    gdown.download("https://drive.google.com/uc?id=YOUR_FILE_ID", MODEL_PATH, quiet=False)

model = load_model(MODEL_PATH)